[package]
name = "plague-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "functionality"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"
